### ISSUE TITLE
Error: WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by aleksvel** [SamaraPainter/CS451-002Group3#8]
This bug is unlikely to be encountered because it appears only when both clients close their connections simultaneously. As a result the server crashes.

To reproduce the bug do the following:

1. Connect to the server in a browser tab
2. Connect to the server in a second browser tab
3. Close the browser

The console error message:

.\CS451-002Group3\src\node_modules\ws\lib\websocket.js:328
      throw err;
      ^

Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.send (D:\Projects\CS451-002Group3\src\node_modules\ws\lib\websocket.js:322:19)
    at WebSocket.onPlayerClose (D:\Projects\CS451-002Group3\src\server.js:32:24)
    at WebSocket.onClose (D:\Projects\CS451-002Group3\src\node_modules\ws\lib\event-target.js:124:16)
    at emitTwo (events.js:131:20)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (D:\Projects\CS451-002Group3\src\node_modules\ws\lib\websocket.js:180:10)
    at Socket.socketOnClose (D:\Projects\CS451-002Group3\src\node_modules\ws\lib\websocket.js:805:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)

**Comment by Korede-TA** [comment]
Is there any way to fail gracefully or catch the error? Otherwise, feel free to close if it's an unlikely bug.
